// import MobileModule from "./module/MobileModule.js";
// import AosModule from "./module/AosModule.js";
import BtnToTopModule from "./module/BtnToTopModule.js";
// import PopupModule from "./module/PopupModule.js";
import SwiperModule from "./module/SwiperModule.js";
// import LoadModule from "./module/LoadModule.js";
// import LoadMoreModule from "./module/LoadMoreModule.js";
// import CheckModule from "./module/CheckModule.js";
// import GalleryModule from "./module/GalleryModule.js";
// import TabModule from "./module/TabModule.js";
import HeaderModule from "./module/HeaderModule.js";
import SideModule from "./module/SideModule.js";
// import ShowHideModule from "./module/ShowHideModule.js";
// import OpenPopup from "./module/OpenPopup.js";
import SmoothScrollModule from "./module/SmoothScrollModule.js";
import Animated from "./module/Animated.js";
import CollapseModule from "./module/CollapseModule.js";
import scrollContent from "./module/ScrollContent.js";
// import ShowImgModule from "./module/ShowImgModule.js";
// import ParallaxModule from "./module/ParallaxModule.js";
import CountUpModule from "./module/CountUpModule.js";
import ScrollDesktop from "./module/ScrollDesktop.js";
import GsapModule from "./module/GsapModule.js";
import ProgressScroll from "./module/ProgressScroll.js";
import DropDownModule from "./module/DropDownModule.js";
import select2Module from "./module/select2Module.js";
import plyrModule from "./module/plyrModule.js";
// import SelectIsotope from "./module/SelectIsotope.js";

window.addEventListener("DOMContentLoaded", () => {
  select2Module();
  DropDownModule();
  // MobileModule();
  // AosModule();
  BtnToTopModule();
  // PopupModule();
  SwiperModule();
  // LoadModule();
  // CheckModule();
  // SearchModule();
  // GalleryModule();
  // TabModule();
  // IsotopeModule();
  HeaderModule();
  SideModule();
  // ShowHideModule();
  // OpenPopup();
  // Animated();
  SmoothScrollModule();
  // LoadMoreModule();
  CollapseModule();
  // CmtModule();
  scrollContent();
  // ShowImgModule();
  // ParallaxModule();
  CountUpModule();
  // SelectIsotope();
  ScrollDesktop();
  GsapModule();
  ProgressScroll();
  plyrModule();
});
